services:
  potato-dashboard:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_CLOUD_TOKEN=${NUXT_CLOUD_TOKEN}
      - NUXT_PUBLIC_CLOUD_BASE_URL=${NUXT_PUBLIC_CLOUD_BASE_URL}
      - WS_BASE_URL=${WS_BASE_URL}
      - WS_API_KEY=${WS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}