services:
  potato-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      args:
        # You might want to set this to a different value if you are running the OpenAPI server on a different machine or port
        - OPENAPI_ENDPOINT=http://host.docker.internal:8080/openapi
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - NUXT_CLOUD_TOKEN=${NUXT_CLOUD_TOKEN}
      - NUXT_PUBLIC_WS_BASE_URL=${NUXT_PUBLIC_WS_BASE_URL}